version: "3.9"

services:
  newsletter_db:
    container_name: newsletter_db
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: newsletter
    ports:
      - "5432:5432"
    volumes:
      - newsletter_db_data:/var/lib/postgresql/data
  newsletter_api:
    container_name: newsletter_api
    restart: on-failure
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - newsletter_db

volumes:
  newsletter_db_data: {}
